### ISSUE TITLE
rocci+voms: error "Response does not contain the www-authenticate header"

### ISSUE THREAD

**Issue by kutovskiy** [gwdg/rOCCI-server#87]
Hello all!

I am trying to deploy a testbed with rOCCI-server and OpenNebula 4.12.1 following https://wiki.egi.eu/wiki/rOCCI:ROCCI-server_Admin_Guid. rOCCI components are installed from packages on CentOS 7.3.1611. rOCCI-server and OpenNebula front-end node are deployed on the same host.
Basic and x509 authentication with curl works fine (i.e. I am getting a model listing) but occi client doesn't work neither with x509 nor voms. My goal is to have voms authentication working.
I am running occi-cli and voms-cli commands from docker container an image for what is provided by EGI FedCloud.

occi@d8b4b3fd2d07:~$ voms-proxy-init -voms testvo --rfc
Enter GRID pass phrase:
Your identity: /C=CO/O=ORG/OU=UNIT/CN=John Smith
Creating temporary proxy ................................................................. Done
Contacting  voms.domain.org:15003 [/C=CO/O=ORG/OU=UNIT/CN=voms.domain.org] "testvo" Done
Creating proxy ................................... Done
Your proxy is valid until Tue Jan 17 22:46:12 2017

occi@d8b4b3fd2d07:~$ voms-proxy-info -all
subject   : /C=CO/O=ORG/OU=UNIT/CN=John Smith/CN=2248071205
issuer    : /C=CO/O=ORG/OU=UNIT/CN=John Smith
identity  : /C=CO/O=ORG/OU=UNIT/CN=John Smith
type      : RFC compliant proxy
strength  : 1024 bits
path      : /tmp/x509up_u1000
timeleft  : 11:59:51
key usage : Digital Signature, Key Encipherment
=== VO testvo extension information ===
VO        : testvo
subject   : /C=CO/O=ORG/OU=UNIT/CN=John Smith
issuer    : /C=CO/O=ORG/OU=UNIT/CN=voms.domain.org
attribute : /testvo/Role=NULL/Capability=NULL
timeleft  : 11:59:51
uri       : voms.domain.org:15003

occi@d8b4b3fd2d07:~$ export X509_USER_PROXY=`voms-proxy-info -path` 

occi@d8b4b3fd2d07:~$ occi -e https://vm221-20.domain.org:11443/ --auth x509 --voms  --user-cred $X509_USER_PROXY --action list --resource os_tpl                 
F, [2017-01-17T10:53:43.488170 #1775] FATAL -- : [rOCCI-cli] An error occurred! Message: Response does not contain the www-authenticate header, fallback failed!

The output of the same command but with debug enabled I put into separate [file](https://github.com/gwdg/rOCCI-server/files/710472/rocci_voms_auth_output.txt) due to its big size.

Both user and host certificates were issued by our local CA. I put CA credentials in /etc/grid-security/certificates/ on both rOCCI+OpenNebula and occi-cli hosts. LSC-file for testvo is in /etc/grid-security/vomsdir folder on rOCCI-OpenNebula host.

test VOMS user in OpenNebula was created by the following command:
[oneadmin@fn]$ oneuser create johnvoms '/C=CO/O=ORG/OU=UNIT/CN=John Smith/VO=testvo/Role=NULL/Capability=NULL' --driver x509

/var/log/one/oned.log:
Tue Jan 17 11:09:55 2017 [Z0][AuM][D]: Message received: AUTHENTICATE SUCCESS 53 -

/var/log/occi-server/production.log:
2017-01-17 11:09:55.541 [ WARN  ] [5b5664cd-1ed3-4840-ac6f-424d7e78b116] [Backend] Failed to authenticate user: User could not be authenticated! (pid:22440)
2017-01-17 11:09:55.542 [ INFO  ] [5b5664cd-1ed3-4840-ac6f-424d7e78b116] Completed 401 Unauthorized in 79ms (Views: 0.1ms) (pid:22440)
2017-01-17 11:09:55.543 [ WARN  ] [5b5664cd-1ed3-4840-ac6f-424d7e78b116] [AuthN] [UnauthorizedController] Authentication failed: Authentication failed! The following strategies are supported "voms, x509, basic"! (pid:22440)
2017-01-17 11:09:55.543 [ WARN  ] [5b5664cd-1ed3-4840-ac6f-424d7e78b116] [AuthN] [UnauthorizedController] Responding with 401 {"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff"} (pid:22440)

There is nothing interesting/relevant in apache log.

I would appreciate if someone could help me with enabling voms authentication for my rOCCI+OpenNebula deployment.

**Comment by arax** [comment]
Hi,

could you switch rOCCI-server to `debug` mode and try again? `/var/log/occi-server/production.log` will contain step-by-step logs from the authentication process.

https://github.com/EGI-FCTF/rOCCI-server/blob/master/examples/etc/apache2/sites-available/occi-ssl#L85

**Comment by kutovskiy** [comment]
Thanks for the prompt reply! [rocci-server_log.txt](https://github.com/gwdg/rOCCI-server/files/710535/rocci-server_log.txt) is attached.

**Comment by arax** [comment]
From
```
  0 2017-01-17 12:29:21.788 [ DEBUG ] [6553ee5a-9ed3-4827-9087-67191c879923] [AuthN] [AuthenticationStrategies::VomsStrategy] Checking for applicability (pid:22440)                                               
  1 2017-01-17 12:29:21.789 [ DEBUG ] [6553ee5a-9ed3-4827-9087-67191c879923] [AuthN] [AuthenticationStrategies::VomsStrategy] SSL_CLIENT_S_DN: "/C=CO/O=ORG/OU=UNIT/CN=John Smith/CN=2248071205" (pid:22440)
  2 2017-01-17 12:29:21.791 [ DEBUG ] [6553ee5a-9ed3-4827-9087-67191c879923] [AuthN] [AuthenticationStrategies::VomsStrategy] GRST_CRED_0: "X509USER 1464460639 1495996639 1 /C=CO/O=ORG/OU=UNIT/CN=John Smith"        …(pid:22440)
  3 2017-01-17 12:29:21.792 [ DEBUG ] [6553ee5a-9ed3-4827-9087-67191c879923] [AuthN] [AuthenticationStrategies::VomsStrategy] GRST_CRED_1: "GSIPROXY 1484638872 1484682372 1 /C=CO/O=ORG/OU=UNIT/CN=John Smith/        …CN=2248071205" (pid:22440)
  4 2017-01-17 12:29:21.794 [ DEBUG ] [6553ee5a-9ed3-4827-9087-67191c879923] [AuthN] [AuthenticationStrategies::VomsStrategy] GRST_CRED_2: nil (pid:22440)
  5 2017-01-17 12:29:21.795 [ DEBUG ] [6553ee5a-9ed3-4827-9087-67191c879923] [AuthN] [AuthenticationStrategies::VomsStrategy] Strategy is not applicable! (pid:22440)
```
I can tell that your apache/gridsite set-up is not working correctly. rOCCI-server is not getting the required information about VOMS extensions in your proxy. This information is provided by `mod_gridsite` as ENV variables. `GRST_CRED_2: nil` means that no VOMS extensions were sent down from `mod_gridsite`.

You can try turning on apache/mod_gridsite debugging and looking for more information in httpd logs.

**Comment by kutovskiy** [comment]
I set 'LogLevel debug' in /etc/httpd/conf.d/occi-ssl.conf and /etc/httpd/conf.d/zgridsite.conf. Restart httpd. Run another occi query and the relevant part of /var/log/httpd/error_log can be found
[here](https://github.com/gwdg/rOCCI-server/files/710925/httpd_errors_log.txt) (I replaced sensitive info in it).

**Comment by arax** [comment]
I don't see anything suspicious in the log. Let's get back to `/var/log/occi-server/production.log`.
Can you turn on request logging in
https://github.com/EGI-FCTF/rOCCI-server/blob/master/examples/etc/apache2/sites-available/occi-ssl#L86 and search the rOCCI-server log for lines containing long hashes? These should contain (among other things) all ENV variables passed from Apache2 to rOCCI-server. They will also contain A LOT of sensitive information, just so you know.

**Comment by kutovskiy** [comment]
Here is a relevant [part](https://github.com/gwdg/rOCCI-server/files/711164/occi-server_log_v2.txt) of production.log with "SetEnv ROCCI_SERVER_LOG_REQUESTS_IN_DEBUG yes" in /etc/httpd/conf.d/occi-ssl.conf (sensitive info is removed/replaced).

**Comment by arax** [comment]
Yep. There is no `GRST_CRED_X` ENV variable containing VOMS extension information. This is most definitely a gridsite issue. I would recommend contacting gridsite developers @ https://github.com/CESNET/gridsite as this requires a much deeper knowledge of mod_gridsite.

**Comment by kutovskiy** [comment]
Boris, thanks a lot for spending time and efforts! I'll try to follow your suggestion to contact gridsite developers.

**Comment by kutovskiy** [comment]
While I am failing to run rOCCI-server with x509+voms authentication I would like to try to run rOCCI-server with OpenNebula at least with x509 one but I am getting the same error as mentioned in the issue's title, i.e. "[rOCCI-cli] An error occurred! Message: Response does not contain the www-authenticate header, fallback failed!".
There is a separate user testx509 in opennebula what was created by the following command:
oneuser create testx509 '/C=CO/O=ORG/OU=UNIT/CN=John Smith' --driver x509

The following command using curl works file, i.e. it prints model listing:
curl --cert ~/.globus/usercert.pem:<password>. --key ~/.globus/userkey.pem https://vm221-20.domain.org:11443/-/

But any occi's ones produce errors (or asks for a password and produce error):
occi -e https://vm221-20.domain.org:11443/ --auth x509 --user-cred ~/.globus/usercert.pem --action list --resource compute
Enter a password: ******************
F, [2017-01-19T15:33:55.554657 #1904] FATAL -- : [rOCCI-cli] An X509 error occurred! Please, make sure you are using the right password and the file contains both your certificate and your private key! Message: Neither PUB key nor PRIV key: nested asn1 error

occi@d8b4b3fd2d07:~$ occi -e https://vm221-20.domain.org:11443/ --auth x509 --user-cred /tmp/x509up_u1000 --action list --resource compute     
Enter a password: ****************
F, [2017-01-19T15:34:16.692210 #1910] FATAL -- : [rOCCI-cli] An error occurred! Message: Response does not contain the www-authenticate header, fallback failed!

It's not clear from https://wiki.egi.eu/wiki/HOWTO11_How_to_use_the_rOCCI_Client and from 'occi -h|grep user-cred' what is a proper syntax for using pure x509 authentication. Should I use proxy certificate generated by voms-proxy-init or I need to somehow merge x509 cert with private key into single file ~/.globus/usercred.pem what by default occi expects to find? Why does occi ask me for a password  in case of proxy certificate?

I am not attaching a logs since I suspect that I misuse occi and just need to fix a syntax I am using. But I am ready to provide a logs in case of necessity.

**Comment by alansill** [comment]
Just a quick check - have you tried using extended-attribute proxies from a real VOMS server, rather than a “domain.org<http://domain.org>” test VOMS? If so, do you see the same results?


On Jan 19, 2017, at 6:41 AM, kutovskiy <notifications@github.com<mailto:notifications@github.com>> wrote:


While I am failing to run rOCCI-server with x509+voms authentication I would like to try to run rOCCI-server with OpenNebula at least with x509 one but I am getting the same error as mentioned in the issue's title, i.e. "[rOCCI-cli] An error occurred! Message: Response does not contain the www-authenticate header, fallback failed!".
There is a separate user testx509 in opennebula what was created by the following command:
oneuser create testx509 '/C=CO/O=ORG/OU=UNIT/CN=John Smith' --driver x509

The following command using curl works file, i.e. it prints model listing:
curl --cert ~/.globus/usercert.pem:. --key ~/.globus/userkey.pem https://vm221-20.domain.org:11443/-/

But any occi's ones produce errors (or asks for a password and produce error):
occi -e https://vm221-20.domain.org:11443/ --auth x509 --user-cred ~/.globus/usercert.pem --action list --resource compute
Enter a password: ******************
F, [2017-01-19T15:33:55.554657 #1904] FATAL -- : [rOCCI-cli] An X509 error occurred! Please, make sure you are using the right password and the file contains both your certificate and your private key! Message: Neither PUB key nor PRIV key: nested asn1 error

occi@d8b4b3f<https://github.com/occi/rOCCI-server/commit/d8b4b3fd2d07>:~$ occi -e https://vm221-20.domain.org:11443/ --auth x509 --user-cred /tmp/x509up_u1000 --action list --resource compute
Enter a password: ****************
F, [2017-01-19T15:34:16.692210 #1910] FATAL -- : [rOCCI-cli] An error occurred! Message: Response does not contain the www-authenticate header, fallback failed!

It's not clear from https://wiki.egi.eu/wiki/HOWTO11_How_to_use_the_rOCCI_Client and from 'occi -h|grep user-cred' what is a proper syntax for using pure x509 authentication. Should I use proxy certificate generated by voms-proxy-init or I need to somehow merge x509 cert with private key into single file ~/.globus/usercred.pem what by default occi expects to find? Why does occi ask me for a password in case of proxy certificate?

I am not attaching a logs since I suspect that I misuse occi and just need to fix a syntax I am using. But I am ready to provide a logs in case of necessity.

**Comment by arax** [comment]
Hi @kutovskiy ,
for rOCCI-cli, the difference is in using `--auth x509` vs. `--auth x509 --voms`. The first one will always ask for a password and the second one will never ask for a password. As you correctly pointed out, our EGI documentation does not provide information on this topic. That's because in EGI infrastructure we never use (personal) X.509 certificates directly, they are always used only as a source for short-lived proxies.

Now to the problem at hand, when using `--auth x509` (__without `--voms`__) you have to provide `usercred.pem` which contains both your certificate and private key in PEM form. If you have a PKCS12 file (`*.p12`), that should work as well.

**Comment by kutovskiy** [comment]
**alansill**, thanks for trying to help me! For my tests I am using our local VOMS server which works fine for other VOs on our test grid infrastructure. The domain.org is just replacement for our real domain.

**arax**, thanks for your clarifications!
I've just deployed rocci-server on CentOS 6.8 x64 and configured it from scratch but I am still getting  the same result with occi-cli+x509+voms. I thought my problem was in using too fresh version of gridsite package (2.3.3 on CentOS 7.3) but with 2.2.6 on CentOS 6.8 the error is the same:
` [rOCCI-cli] An error occurred! Message: Response does not contain the www-authenticate header, fallback failed!` 
Could it be related that hostname for rOCCI-server and cloud front-end nodes I am using is not in DNS but just in /etc/hosts on both servers and client? Maybe some components are trying to query DNS and not /etc/hosts and fails.

**Comment by arax** [comment]
That should not cause any problems. Have you tried with X.509 only? Without VOMS.

**Comment by kutovskiy** [comment]
`openssl pkcs12 -export -in usercert.pem -inkey userkey.pem  -out usercert.p12`

`occi@d8b4b3fd2d07:~/.globus$ occi -e https://vm221-20.domain.org:11443/ --auth x509 --user-cred ~/.globus/usercert.p12 --action list --resource os_tpl`
`Enter a password: ********`
`F, [2017-01-20T23:13:21.092141 #2090] FATAL -- : [rOCCI-cli] An error occurred! Message: Response does not contain the www-authenticate header, fallback failed!`

`occi@d8b4b3fd2d07:~/.globus$ occi -e https://vm221-40.domain.org:11443/ --auth x509 --user-cred ~/.globus/usercert.p12 --action list --resource os_tpl `
`Enter a password: ********`
`<empty string here and "Completed 200 OK in 437ms (Views: 4.2ms) (pid:31741)" in the occi-server log file>`

So it seems like x509 authentication works with vm221-40 (CentOS 6.8 x64, gridsite-2.2.6, occi-server-1.1.9+20160622122112-1.el6.x86_64) but doesn't with vm221-20 (CentOS 7.3 x64, gridsite-2.3.3, occi-server-1.1.9+20160622124300-1.el7.x86_64).
VOMS authentication doesn't work with any of them.
A relevant parts of occi-server log files:
[occi-server_centos-7_x509.log.txt](https://github.com/gwdg/rOCCI-server/files/720436/occi-server_centos-7_x509.log.txt)
[occi-server_centos-6_voms.log.txt](https://github.com/gwdg/rOCCI-server/files/720435/occi-server_centos-6_voms.log.txt)

**Comment by arax** [comment]
Well, it looks like VOMS authentication is still broken on CentOS 6, no change there. Has anyone responded to the issue you opened on gridsite?

For CentOS 7, X.509 auth is broken because new Apache2 versions (AFAIK, 2.4+) use a different DN format. In you VHost file, you should see
```
SSLOptions +StdEnvVars +ExportCertData +LegacyDNStringFormat
```
Is `+LegacyDNStringFormat` there?

**Comment by kutovskiy** [comment]
> Well, it looks like VOMS authentication is still broken on CentOS 6, no change there. Has anyone responded to the issue you opened on gridsite?

no, unfortunately nobody has responded

> Is +LegacyDNStringFormat there?

Initially that option was there but re-deploying rOCCI-server from scratch on CentOS 6.8 and comparing with EGI rOCCI-server Admin [Guide](https://wiki.egi.eu/wiki/rOCCI:ROCCI-server_Admin_Guide) yesterday I had removed that option from occi-ssl.conf file. But  you are right as soon as I add it back the x509 auth works fine with PKCS12 user cert and rOCCI-server on CentOS 7.

**Arax**, thank a lot for taking time to have a look and reply!

**Comment by arax** [comment]
@kutovskiy Happy to help! I will do my best to prod my colleagues to respond to the gridsite issue ASAP.

**Comment by kutovskiy** [comment]
Thank you, **arax**!
